pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                    credentialsId: 'github_token',
                    url: 'https://github.com/Ash-sungho/docker-demo.git'
            }
        }
        stage('Build') {
            steps {
                echo "Building.."
            }
        }
        stage('Test') {
            steps {
                echo "Test222.."
            }
        }
        stage('Deploy') {
            steps {
                 echo "Deploy.."
            }
        }
    }
}